service: stdb
frameworkVersion: "3"
useDotenv: true

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, env:AWS_STAGE, 'dev'}
  region: ${opt:region, env:AWS_REGION, 'eu-central-1'}
  stackName: ${self:service}-${self:provider.stage}

custom:
  webpack:
    webpackConfig: webpack.config.js
    packager: "yarn"
    includeModules:
      forceExclude:
        - aws-sdk

functions:
  - ${file(src/insert-stream/trigger.yml)}

resources:
  - ${file(singleTable.yml)}

  - Outputs:
      AwsRegion:
        Value: ${opt:region, self:provider.region}
      SingleTableID:
        Value: !Ref SingleTable
      SingleTableArn:
        Value: !GetAtt SingleTable.Arn
      CFStack:
        Value: ${self:provider.stackName}
