name: CI

on:
  push:
    branches:
      - 3-cicd-setup

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Manually install Serverless Framewrok
        run: yarn global add serverless

      - name: Install project dependencies
        run: yarn install --frozen-lockfile

      - name: Deploy on ephemeral environment
        run: serverless deploy --stage ${{ github.run_id }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Perform tests for api service
        run: cd api && yarn export-env ${{ github.run_id }} && yarn test-ci && cd ../
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Remove from ephermeral environment
        run: serverless remove --stage ${{ github.run_id }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}