name: Deploy

on:
  push:
    branches:
      - dev
      - staging
      - prod

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Manually install Serverless Framewrok
      run: yarn global add serverless

    - name: Install project dependencies
      run: yarn install --frozen-lockfile

    - name: Serverless deploy Deploy on ephemeral environment
      run: serverless deploy --stage ${{ github.ref_name }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}